export default {
    FETCH_ALL: 'FETCH_ALL',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    LIKE: 'LIKE',
    AUTH: 'AUTH',
    LOGOUT: 'LOGOUT',
    FETCH_BY_SEARCH : 'FETCH_BY_SEARCH',
    FETCH_POST : 'FETCH_POST',
    END_LOADING : 'END_LOADING',
    START_LOADING : 'START_LOADING',
    COMMENT : 'COMMENT'
}